---
- name: MySql Jar Downloading
  get_url:
    url:  https://s3.amazonaws.com/teraesb/mysql-connector-java-5.1.45-bin.jar
    dest: "{{ API_Home}}/repository/components/lib"
    owner: "{{ app_user }}" 
    group: "{{ app_user }}"
    mode: 0740
