---

- name: Downloading the Lates JAVA RPM
  get_url:
        url: http://download.oracle.com/otn-pub/java/jdk/8u162-b12/0da788060d494f5095bf8624735fa2f1/jdk-8u162-linux-x64.rpm
        dest: /opt
        mode: 0744
        headers: 'Cookie: oraclelicense=accept-securebackup-cookie'

- name: install Java
  yum:
    name: /opt/jdk-8u162-linux-x64.rpm
    state: present


- name: set Java version as default
  alternatives:
    name: java
    link: "/usr/bin/java"
    path: "/usr/java/jdk1.8.0_162/jre/bin/java"

- name: Removing the RPM file
  file: dest=/opt/jdk-8u162-linux-x64.rpm  state=absent


- name: ADD Environment Variables     
  lineinfile: "dest=/etc/environment  regexp=^JAVA_HOME=  line=JAVA_HOME=/usr/java/jdk1.8.0_162/jre"
