--- 
- hosts: api
  gather_facts: no
  pre_tasks:
  - name: Define port offset 
    set_fact:
      port_offset: true
    when: role | length > 1
  tasks:
    - setup:

- hosts: cluster
  gather_facts: no
  become: true
  become_user: root
  roles:
      - Java8
      - APISetup
      - Jar

- hosts: publisher_cluster
  gather_facts: no
  become: true
  become_user: root
  roles:
      - Publisher_ClusterSetup

- hosts: store_cluster
  gather_facts: no
  become: true
  become_user: root
  roles:
      - Store_ClusterSetup


- hosts: keyManager_cluster
  gather_facts: no
  become: true
  become_user: root
  roles:
      - KeyManager_ClusterSetup

- hosts: traficManager_cluster
  gather_facts: no
  become: true
  become_user: root
  roles:
      - TraficManager_ClusterSetup

- hosts: gateway_cluster
  gather_facts: no
  become: true
  become_user: root
  roles:
      - Gateway_ClusterSetup


# - hosts: dbservers
#   gather_facts: no
#   become: true
#   become_user: root
#   roles:
#       - APISetup
#       - MySqlServer

# - hosts: nginx
#   gather_facts: no
#   become: true
#   become_user: root
#   roles:
#       - Nginx