--- 
- hosts: api
  gather_facts: no
  tasks:
    - setup:

- hosts: cluster
  gather_facts: no
  become: true
  become_user: root
  roles:
      # - Java8
      # - APISetup
      # - Jar
      - ClusterSetup
      - DbSetup
      
# - hosts: dbservers
#   gather_facts: no
#   become: true
#   become_user: root
#   roles:
#       - APISetup
#       - MySqlServer

# - hosts: nginx
#   gather_facts: no
#   become: true
#   become_user: root
#   roles:
#       - Nginx