---
# common vars file for mysql_server
API_Home: /opt/API/wso2am-2.1.0


#Credentials
mysql_root_pass: ""
mysql_root_username: root
mysql_users_pass: apiadmin

# Databases.
mysql_databases:
  - apimgtdb
  - userdb
  - regdb
  - statdb

mysql_users:
  - apiadmin
