--- 
  - name: Copy the api-manager.xml
    template: src=api-manager.xml.j2 dest={{ doc_root }}/repository/conf/api-manager.xml owner="{{ app_user }}" group="{{ app_user }}" mode=0644

  - name: Copy the Axis2.xml
    template: src=axis2.xml.j2 dest={{ doc_root }}/repository/conf/axis2/axis2.xml owner="{{ app_user }}" group="{{ app_user }}" mode=0644


  - name: Set DNS for worker in Gateway Manager    
    lineinfile: "dest=/etc/hosts  regexp={{ groups['gateway_Worker'][0] }}  line='{{ groups['gateway_Worker'][0] }} {{ gateway_domain }}'"
    when: role == "Gateway" and subrole == "mgt"

  - name: Set DNS for Manager in Gateway worker    
    lineinfile: "dest=/etc/hosts  regexp={{ groups['gateway_Manager'][0] }}  line='{{ groups['gateway_Manager'][0] }} mgt.{{ gateway_domain }}'"
    when: role == "Gateway" and subrole == "wkr"

  - name: Copy the carbon.XMl
    template: src=carbon.xml.j2 dest={{ doc_root }}/repository/conf/carbon.xml owner="{{ app_user }}" group="{{ app_user }}" mode=0644
    when: role == "Gateway"

  # - name: Copy the catalina-server.XML
  #   template: src=catalina-server.xml.j2 dest={{ doc_root }}/repository/conf/tomcat/catalina-server.xml owner="{{ app_user }}" group="{{ app_user }}" mode=0644

  # - name: Copy the rsync script
  #   template: src=rsync-for-ei-depsync.sh.j2 dest={{ doc_root }}/repository/rsync-for-ei-depsync.sh owner="{{ app_user }}" group="{{ app_user }}" mode=0744
  #   when: role == "node1"

  # - name: Copy the node list
  #   template: src=nodes-list.txt.j2 dest={{ doc_root }}/repository/nodes-list.txt owner="{{ app_user }}" group="{{ app_user }}" mode=0744
  #   when: role == "node1"
  
  # - name: Copy the Ini.d Script
  #   template: src=esb.j2 dest=/etc/init.d/esb owner="root" group="root" mode=0744

  # - name: "Creating the Rsync in nodes"
  #   cron:
  #     name: "Creating the Rsync in nodes"
  #     job: "{{ doc_root }}/repository/rsync-for-ei-depsync.sh"
  #   when: role == "node1"