---

# Check and install MySQL packages
- name: Check if MySQL is already installed.
  stat: path=/etc/init.d/mysql
  register: mysql_installed
  tags: setup

- name: Update apt cache if MySQL is not yet installed.
  apt: update_cache=yes
  when: mysql_installed.stat.exists == false
  tags: setup

- name: Ensure MySQL Python libraries are installed.
  apt: "name={{ mysql_driver }} state=installed"
  when: mysql_installed.stat.exists == false
  tags: setup

- name: Ensure MySQL packages are installed.
  apt: "name={{ item }} state=installed"
  with_items: "{{ mysql_packages }}"
  notify: restart mysql
  when: mysql_installed.stat.exists == false
  tags: setup


- name: Commenting the Port Bind   
  lineinfile: "dest=/etc/mysql/mysql.conf.d/mysqld.cnf  regexp=^bind-address  line=#bind-address=127.0.0.1"
  notify: restart mysql