--- 
  
  - name: Copy the master-datasources.xml 
    template: src=master-datasources.xml.j2 dest={{ doc_root }}/repository/conf/datasources/master-datasources.xml owner="{{ app_user }}" group="{{ app_user }}" mode=0644

  - name: Copy the api-manager.xml
    template: src=api-manager.xml.j2 dest={{ doc_root }}/repository/conf/api-manager.xml owner="{{ app_user }}" group="{{ app_user }}" mode=0644

  - name: Copy the Axis2.xml
    template: src=axis2.xml.j2 dest={{ doc_root }}/repository/conf/axis2/axis2.xml owner="{{ app_user }}" group="{{ app_user }}" mode=0644


  - name: Copy the carbon.XMl
    template: src=carbon.xml.j2 dest="{{ doc_root }}/repository/conf/carbon.xml" owner="{{ app_user }}" group="{{ app_user }}" mode=0644

  - name: Set DNS for worker in Gateway Manager    
    lineinfile: "dest=/etc/hosts  regexp={{ groups['gateway_Worker'][0] }}  line='{{ groups['gateway_Worker'][0] }} {{ gateway_domain }}'"
    when:  subrole == "mgt"

  - name: Set DNS for Manager in Gateway worker    
    lineinfile: "dest=/etc/hosts  regexp={{ groups['gateway_Manager'][0] }}  line='{{ groups['gateway_Manager'][0] }} mgt.{{ gateway_domain }}'"
    when: subrole == "wkr"
      

  
